on:
  issues:
    types:
      - opened
  issue_comment:
    types:
      - created

jobs:
  create_pull_request:
    if: ${{ (contains(github.event.issue.body, '#import') && !github.event.comment) || contains(github.event.comment.body, '#import') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cat > "exercises/$(date +%Y)/actions-import/${{ github.event.issue.title }}/exercise.md" << EOF
          ${{ github.event.issue.body }}
          EOF
      - run: |
          git checkout -b "import#${{ github.event.issue.number }}"
          git add .
          git commit -m "import ${{ github.event.issue.title }}"
          git push origin "import#${{ github.event.issue.number }}"
      - run: |
          gh issue comment ${{ github.event.issue.html_url }} -b "Hi, I am your import-bot. :wave: I have created the branch import#${{github.event.issue.number}} for you! :muscle:"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
